import Link from "next/link";
import { WorkspaceShell } from "@/components/dashboard/workspace-shell";
import { requireClinicPermission } from "@/lib/auth/guards";
import { PERMISSIONS } from "@/lib/auth/permissions";
import { getInventoryOverview } from "@/lib/pharmacy/inventory";
import styles from "@/components/dashboard/workspace-page.module.css";
import { createMedicineAction, receiveStockAction, adjustStockAction, returnStockToSupplierAction, recordExpiredStockAction, disposeExpiredStockAction } from "../inventory-actions";

export default async function PharmacyInventoryPage() {
  const context = await requireClinicPermission(PERMISSIONS.PHARMACY_VIEW);
  const overview = await getInventoryOverview(context);
  const canAdjust = context.permissions.has(PERMISSIONS.PHARMACY_STOCK_ADJUST);
  return <WorkspaceShell context={context} activeHref="/pharmacy"><div className={styles.page}>
    <nav><Link href="/pharmacy" className={styles.backLink}>← Back to Pharmacy</Link></nav>
    <header className={styles.hero}><p className={styles.eyebrow}>Pharmacy inventory</p><h1 className={styles.title}>Inventory & stock</h1><p className={styles.description}>Manage medicine batches with controlled receiving, adjustments, returns and expiry/disposal workflows.</p><p><Link href="/pharmacy/movements" className={styles.secondaryButton}>View stock movement history</Link></p></header>
    <section className={styles.cardGrid}><article className={styles.card}><p className={styles.cardLabel}>Medicines</p><p className={styles.cardValue}>{overview.medicines.length}</p></article><article className={styles.card}><p className={styles.cardLabel}>Batches</p><p className={styles.cardValue}>{overview.batches.length}</p></article><article className={styles.card}><p className={styles.cardLabel}>Usable low stock</p><p className={styles.cardValue}>{overview.medicines.filter(m=>m.totalQuantity<=m.reorderLevel).length}</p></article><article className={styles.card}><p className={styles.cardLabel}>Expiry watch</p><p className={styles.cardValue}>{overview.batches.filter(b=>b.quantity>0 && b.expiryDate<=new Date(Date.now()+30*24*60*60*1000)).length}</p></article></section>
    {canAdjust ? <><section className={styles.section}><h2 className={styles.sectionTitle}>Add medicine</h2><form action={createMedicineAction} className={styles.patientForm}><div className={styles.formGrid}><label className={styles.field}><span>Medicine name</span><input name="name" required /></label><label className={styles.field}><span>Strength</span><input name="strength" /></label><label className={styles.field}><span>Form</span><input name="form" /></label><label className={styles.field}><span>Reorder level</span><input name="reorderLevel" type="number" min="0" defaultValue="0" required /></label></div><div className={styles.formActions}><button className={styles.primaryButton}>Add medicine</button></div></form></section><section className={styles.section}><h2 className={styles.sectionTitle}>Receive stock</h2><p className={styles.sectionDescription}>Existing batch metadata must match exactly. This prevents accidental changes to expiry, price or supplier history.</p><form action={receiveStockAction} className={styles.patientForm}><div className={styles.formGrid}><label className={styles.field}><span>Medicine</span><select name="medicineId" required defaultValue=""><option value="" disabled>Select medicine</option>{overview.medicines.map(m=><option key={m.id} value={m.id}>{m.name}{m.strength?` ${m.strength}`:""}</option>)}</select></label><label className={styles.field}><span>Batch number</span><input name="batchNumber" required /></label><label className={styles.field}><span>Expiry</span><input name="expiryDate" type="date" required /></label><label className={styles.field}><span>Quantity</span><input name="quantity" type="number" min="1" required /></label><label className={styles.field}><span>Unit cost</span><input name="unitCost" type="number" min="0" step="0.01" required /></label><label className={styles.field}><span>Selling price</span><input name="sellingPrice" type="number" min="0" step="0.01" required /></label><label className={styles.fieldWide}><span>Supplier</span><input name="supplierName" /></label></div><div className={styles.formActions}><button className={styles.primaryButton}>Receive stock</button></div></form></section></> : null}
    <section className={styles.section}><h2 className={styles.sectionTitle}>Stock batches</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Quantity</th><th>Supplier</th>{canAdjust?<th>Controlled action</th>:null}</tr></thead><tbody>{overview.batches.map(b=><tr key={b.id}><td>{b.medicineName}</td><td>{b.batchNumber}</td><td>{b.expiryDate.toLocaleDateString("en-KE")}</td><td>{b.quantity}</td><td>{b.supplierName||"—"}</td>{canAdjust?<td><div className={styles.formActions}><form action={adjustStockAction}><input type="hidden" name="batchId" value={b.id}/><input name="delta" type="number" step="1" placeholder="± qty" required/><input name="reason" placeholder="Reason" required/><button className={styles.secondaryButton}>Adjust</button></form>{b.quantity>0?<form action={returnStockToSupplierAction}><input type="hidden" name="batchId" value={b.id}/><input name="quantity" type="number" min="1" max={b.quantity} placeholder="Qty" required/><input name="reason" placeholder="Return reason" required/><button className={styles.secondaryButton}>Return</button></form>:null}{b.expiryDate<new Date()&&b.quantity>0?<><form action={recordExpiredStockAction}><input type="hidden" name="batchId" value={b.id}/><input name="quantity" type="number" min="1" max={b.quantity} placeholder="Qty" required/><input name="reason" placeholder="Expiry reason" required/><button className={styles.secondaryButton}>Record expiry</button></form><form action={disposeExpiredStockAction}><input type="hidden" name="batchId" value={b.id}/><input name="quantity" type="number" min="1" max={b.quantity} placeholder="Qty" required/><input name="reason" placeholder="Disposal reason" required/><button className={styles.secondaryButton}>Dispose</button></form></>:null}</div></td>:null}</tr>)}</tbody></table></div></section>
  </div></WorkspaceShell>;
}
